perl -pi -e "s/\-\-debug\-flags\=ExecTicks\,ExecSymbol\,ExecPOM\,Cache\,DRAMPower/\-\-debug\-flags\=Exec\,POMTest\,POMCache\,DRAMPower/g" seconfig_ccc
perl -pi -e "s/\-\-debug\-flags\=ExecTicks\,ExecSymbol\,ExecPOM\,Cache\,DRAMPower/\-\-debug\-flags\=Exec\,POMTest\,POMCache\,DRAMPower/g" seconfig_dram_l24m_default
perl -pi -e "s/\-\-debug\-flags\=ExecTicks\,ExecSymbol\,ExecPOM\,Cache\,DRAMPower/\-\-debug\-flags\=Exec\,POMTest\,POMCache\,DRAMPower/g" seconfig_dram_l24m_l1associate8
perl -pi -e "s/\-\-debug\-flags\=ExecTicks\,ExecSymbol\,ExecPOM\,Cache\,DRAMPower/\-\-debug\-flags\=Exec\,POMTest\,POMCache\,DRAMPower/g" seconfig_dram_l2_l1associate8
perl -pi -e "s/\-\-debug\-flags\=ExecTicks\,ExecSymbol\,ExecPOM\,Cache\,DRAMPower/\-\-debug\-flags\=Exec\,POMTest\,POMCache\,DRAMPower/g" seconfig_ccc
perl -pi -e "s/\-\-debug\-flags\=ExecTicks\,ExecSymbol\,ExecPOM\,Cache\,DRAMPower/\-\-debug\-flags\=Exec\,POMTest\,POMCache\,DRAMPower/g" seconfig_dram_l24m_default
perl -pi -e "s/\-\-debug\-flags\=ExecTicks\,ExecSymbol\,ExecPOM\,Cache\,DRAMPower/\-\-debug\-flags\=Exec\,POMTest\,POMCache\,DRAMPower/g" seconfig_dram_l24m_l1associate8
perl -pi -e "s/\-\-debug\-flags\=ExecTicks\,ExecSymbol\,ExecPOM\,Cache\,DRAMPower/\-\-debug\-flags\=Exec\,POMTest\,POMCache\,DRAMPower/g" seconfig_dram_l2_l1associate8
perl -pi -e "s/\-\-debug\-flags\=ExecTicks\,ExecSymbol\,ExecPOM\,Cache/\-\-debug\-flags\=Exec\,POMTest\,POMCache\,DRAMPower/g" seconfig
perl -pi -e "s/\-\-debug\-flags\=ExecTicks\,ExecSymbol\,ExecPOM\,Cache/\-\-debug\-flags\=Exec\,POMTest\,POMCache\,DRAMPower/g" seconfig_64k_associate8
perl -pi -e "s/\-\-debug\-flags\=ExecTicks\,ExecSymbol\,ExecPOM\,Cache/\-\-debug\-flags\=Exec\,POMTest\,POMCache\,DRAMPower/g" seconfig_64kcache
perl -pi -e "s/\-\-debug\-flags\=ExecTicks\,ExecSymbol\,ExecPOM\,Cache/\-\-debug\-flags\=Exec\,POMTest\,POMCache\,DRAMPower/g" seconfig_cache_associate8
perl -pi -e "s/\-\-debug\-flags\=ExecTicks\,ExecSymbol\,ExecPOM\,Cache/\-\-debug\-flags\=Exec\,POMTest\,POMCache\,DRAMPower/g" seconfig_default_cache
perl -pi -e "s/\-\-debug\-flags\=ExecTicks\,ExecSymbol\,ExecPOM\,Cache/\-\-debug\-flags\=Exec\,POMTest\,POMCache\,DRAMPower/g" seconfig_l24m_default
perl -pi -e "s/\-\-debug\-flags\=ExecTicks\,ExecSymbol\,ExecPOM\,Cache/\-\-debug\-flags\=Exec\,POMTest\,POMCache\,DRAMPower/g" seconfig_l24m_l1associate8
perl -pi -e "s/\-\-debug\-flags\=ExecTicks\,ExecSymbol\,ExecPOM\,Cache/\-\-debug\-flags\=Exec\,POMTest\,POMCache\,DRAMPower/g" seconfig_l2_l1associate8
perl -pi -e "s/\-\-debug\-flags\=ExecTicks\,ExecSymbol\,ExecPOM\,Cache/\-\-debug\-flags\=Exec\,POMTest\,POMCache\,DRAMPower/g" seconfig_l2default
perl -pi -e "s/\-\-debug\-flags\=ExecTicks\,ExecSymbol\,ExecPOM\,Cache/\-\-debug\-flags\=Exec\,POMTest\,POMCache\,DRAMPower/g" seconfig_normal
